version: '3.4'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - appointmentDb
  appointmentDb:
    container_name: appointmentDb
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "CJnEmigeGJLipcRy42MNv"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"